### ISSUE TITLE
fix: admin routing

### ISSUE THREAD

**Issue by VicAv99** [onehungrymind/sermon-beacon#20]
It seems like the side nav for `management` is sending you to the `/management` route, which doesn't exist. Update that to the route `/manage` to get it working again.

Also, as a side note, the `border-bottom` size for the toolbar is too small. Let's up the size to 2px.

**Comment by davidavila2** [comment]
Is this still an issue? I have checked out master and this doesnt seem to be an issue...

![image](https://user-images.githubusercontent.com/38518209/69501822-cbdfa800-0ec5-11ea-9d93-904f5b92a4ee.png)

**Comment by VicAv99** [comment]
Seems like no, just update the border-bottom.
